name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2
      - run: git clone https://github.com/acidanthera/VoodooInput
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Trackpad -configuration Release
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Trackpad -configuration Debug
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Keyboard -configuration Release
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Keyboard -configuration Debug
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Controller -configuration Release
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Controller -configuration Debug
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git*'
      
jobs:
  build:
    name: Upload
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Build/*/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true
