name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: KEXT

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - name: Manage Version
        run: |
          eval $(grep -m 1 "MODULE_VERSION =" VoodooPS2Controller.xcodeproj/project.pbxproj | tr -d ';' | tr -d '\t' | tr -d " ")
          echo "TAG_VER=$MODULE_VERSION" >> $GITHUB_ENV
        
      - name: Build
        uses: actions/checkout@v2
      - run: git clone https://github.com/acidanthera/VoodooInput
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Trackpad -configuration Release -derivedDataPath Build
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Trackpad -configuration Debug -derivedDataPath Build
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Keyboard -configuration Release -derivedDataPath Build
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Keyboard -configuration Debug -derivedDataPath Build
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Controller -configuration Release -derivedDataPath Build
      - run: xcodebuild build -arch x86_64 -scheme VoodooPS2Controller -configuration Debug -derivedDataPath Build
      - run: cd Build/Build/Products/Debug && zip -r -X "../VoodooPS2Controller-${{ github.ref }}-DEBUG.zip" .
      - run: cd ..
      - run: cd Release && zip -r -X "../VoodooPS2Controller-${{ github.ref }}-RELEASE.zip" .
      
      - name: Upload to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: Build/Products/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true
